import pandas as pd
from datetime import datetime
import os

def generate_text_report(df: pd.DataFrame, stats: dict, output_dir: str = "data/processed") -> str:
    """
    Generates a structured text report containing dataset metadata and statistical analysis.

    Args:
        df (pd.DataFrame): The validated dataset.
        stats (dict): The dictionary of statistics calculated by the analyzer.
        output_dir (str): Directory where the report will be saved.

    Returns:
        str: The file path of the generated report.
    """
    print("\n📄 Generating automated text report...")

    # 1. Ensure the output directory exists
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)

    # 2. Get the current timestamp for the analysis metadata
    current_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    # 3. Gather dimensions
    num_rows, num_cols = df.shape

    # 4. Construct the report content
    report_content = f"""==================================================
ENERGY CONSUMPTION ANALYSIS REPORT (AUTOMATED)
==================================================
Date of Analysis:  {current_time}
Data Source:       Red Eléctrica de España (REE)

--------------------------------------------------
1. DATASET METADATA
--------------------------------------------------
- total Rows:      {num_rows}
- Total Columns:   {num_cols}
- Column Names:    {', '.join(df.columns)}

--------------------------------------------------
2. STATISTICAL SUMMARY (DEMAND IN MW)
--------------------------------------------------
- Maximum Demand:  {stats['max']} MW
- Minimum Demand:  {stats['min']} MW
- Mean (Average):  {stats['mean']:.2f} MW
- Median:          {stats['median']:.2f} MW
- Std. Deviation:  {stats['std_dev']:.2f} MW

==================================================
Report successfully generated by Data Pipeline.
==================================================
"""
    
    # 5. Save the report to a file
    output_path = os.path.join(output_dir, "energy_analysis_report.txt")
    try:
        with open(output_path, "w", encoding="utf-8") as file:
            file.write(report_content)
        print(f"✅ Report successfully saved to: '{output_path}'")
        return output_path
    except IOError as e:
        raise RuntimeError(f"Failed to write the report file: {e}")